---
# https://k3d.io/v5.4.1/usage/configfile/#all-options-example
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: prod-east
servers: 1
image: rancher/k3s:v1.32.3-k3s1
ports:
  - port: 32179:32179
    nodeFilters:
      - server:*
  - port: 32180:32180
    nodeFilters:
      - server:*
  - port: 32181:32181
    nodeFilters:
      - server:*
  - port: 32182:32182
    nodeFilters:
      - server:*
  - port: 32280:32280
    nodeFilters:
      - server:*
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
