---
name: Render Argo CD Manifests

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [upstream-update]

permissions:
  contents: write
  pull-requests: write

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: DaneWeber/argo-cd-app-of-apps-of-apps
    steps:
      - name: Checkout downstream repository
        uses: actions/checkout@v4

      - name: Clone upstream repository
        run: |
          git clone https://github.com/${UPSTREAM_REPO}.git upstream
          cd upstream
          git checkout ${{ github.event.client_payload.sha }}
          # Capture commit message and PR number for later use
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP '\(#(\d+)\) *$' | grep -oP '\d+' || true)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render Helm templates
        run: |
          rm -rf rendered-manifests
          pushd upstream
          mv root-application.yaml ../
          ./render.sh
          mv rendered-manifests ../
          popd
          rm -rf upstream

      - name: Commit and push rendered manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update/rendered-manifests-${{ github.event.client_payload.sha }}
          git add rendered-manifests
          git commit -m "render: $COMMIT_MESSAGE ${{ github.event.client_payload.sha }}"
          git push --force origin update/rendered-manifests-${{ github.event.client_payload.sha }}

      - name: Create Pull Request for rendered manifests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: render -- ${{ env.COMMIT_MESSAGE }} ${{ github.event.client_payload.sha }}
          PR_BODY: |
            This PR updates the rendered Argo CD manifests based on upstream commit ${{ github.event.client_payload.sha }}.

            https://github.com/${{ env.UPSTREAM_REPO }}/pull/${{ env.PR_NUMBER }}
          API_URL: https://api.github.com/repos/${{ github.repository }}/pulls
          HEAD: update/rendered-manifests-${{ github.event.client_payload.sha }}
          BASE: ${{ github.event.repository.default_branch || 'main' }}
        run: |
          echo "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$HEAD\",\"base\":\"$BASE\"}"
          curl -s -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            "$API_URL" \
            -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$HEAD\",\"base\":\"$BASE\"}"

      - name: Upload rendered manifests as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered-manifests
